# Set wallpaper (use empty monitor for all, or "DP-1", "eDP-1", etc.)

wallpaper {
    monitor = DP-1
    path = ~/.config/Backgrounds/win_11_red.jpg
    fit_mode = cover
} 

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/Backgrounds/win_11_red.jpg
    fit_mode = cover
} 
