vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

require('user.lazy')
require('user.settings')
require('user.dap')
require('user.telescope')
require('user.keymaps')
require('user.yankHighlight')
require('user.lualine')
require('user.indent_blankline')
require('user.gitsigns')
-- require('user.treesitter')
require('user.lsp')
require('user.cmp')
require("user.bufferline")
require("user.tokyonight")
require("user.toggleterm")
require("user.peek")
require("user.bufferline")
require("user.transparent")
require("user.rust-tools")
require("user.navic")
-- require("user.navbuddy")
require("user.dressing")
require("user.null-ls")
require("user.dadbod")
-- require("user.dap-virtual-text")
-- this is a useless comment
